all:
	pdflatex 03.vmc.tex

clean:
	rm -f *.aux *.out *.log 
	rm -f *.snm *.toc *.nav

mrproper: clean
	rm -f $(SOURCE).terra.pdf $(SOURCE).curiosity.pdf $(SOURCE).utbm.internship.pdf $(SOURCE).utbm.official.pdf
